language: python

python: 3.5

# Use container based infrastructure
sudo: false

env:
  - TOX_ENV=flake8
  - TOX_ENV=py35-dj10-cms34
  - TOX_ENV=py34-dj10-cms34
  - TOX_ENV=py27-dj10-cms34
  - TOX_ENV=py35-dj19-cms33
  - TOX_ENV=py35-dj19-cms32
  - TOX_ENV=py34-dj19-cms33
  - TOX_ENV=py34-dj19-cms32
  - TOX_ENV=py27-dj19-cms33
  - TOX_ENV=py27-dj19-cms32
  - TOX_ENV=py35-dj18-cms33
  - TOX_ENV=py35-dj18-cms32
  - TOX_ENV=py34-dj18-cms33
  - TOX_ENV=py34-dj18-cms32
  - TOX_ENV=py27-dj18-cms33
  - TOX_ENV=py27-dj18-cms32

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls