language: python

# Use container based infrastructure
sudo: false

env:
  - TOX_ENV=flake8
  - TOX_ENV=py35-dj19-cms33
  - TOX_ENV=py35-dj19-cms32
  - TOX_ENV=py34-dj19-cms33
  - TOX_ENV=py34-dj19-cms32
  - TOX_ENV=py27-dj19-cms33
  - TOX_ENV=py27-dj19-cms32
  - TOX_ENV=py35-dj18-cms33
  - TOX_ENV=py35-dj18-cms32
  - TOX_ENV=py34-dj18-cms33
  - TOX_ENV=py34-dj18-cms32
  - TOX_ENV=py34-dj18-cms31
  - TOX_ENV=py27-dj18-cms33
  - TOX_ENV=py27-dj18-cms32
  - TOX_ENV=py27-dj18-cms31
  - TOX_ENV=py34-dj17-cms32
  - TOX_ENV=py34-dj17-cms31
  - TOX_ENV=py34-dj17-cms30
  - TOX_ENV=py27-dj17-cms32
  - TOX_ENV=py27-dj17-cms31
  - TOX_ENV=py27-dj17-cms30
  - TOX_ENV=py27-dj16-cms32
  - TOX_ENV=py27-dj16-cms31
  - TOX_ENV=py27-dj16-cms30
  - TOX_ENV=py26-dj16-cms32
  - TOX_ENV=py26-dj16-cms31
  - TOX_ENV=py26-dj16-cms30

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls